Zorbus\PageBundle\Entity\Page:
    type: entity
    table: zorbus_page_page
    repositoryClass: Zorbus\PageBundle\Entity\PageRepository
    gedmo:
        tree:
            type: nested
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            length: 255
            nullable: false
        subtitle:
            type: string
            length: 255
            nullable: true
        lang:
            type: string
            length: 5
            default: en_US
            nullable: true
        slug:
            type: string
            length: 255
            nullable: true
            gedmo:
                slug:
                    separator: '-'
                    style: default
                    fields:
                        - title
        url:
            type: string
            length: 255
            nullable: false
        theme:
            type: string
            length: 255
            default: layout
            nullable: true
        lft:
            type: integer
            gedmo:
                - treeLeft
        rgt:
            type: integer
            gedmo:
                - treeRight
        root:
            type: integer
            nullable: true
            gedmo:
                - treeRoot
        lvl:
            type: integer
            gedmo:
                - treeLevel
        user_id:
            type: integer
            nullable: true
        enabled:
            type: boolean
            default: true
            nullable: true
        created_at:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updated_at:
            type: datetime
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        parent:
            targetEntity: Zorbus\PageBundle\Entity\Page
            inversedBy: children
            joinColumn:
                name: parent_id
                referencedColumnName: id
                onDelete: SET NULL
            gedmo:
                - treeParent
    oneToMany:
        children:
            targetEntity: Zorbus\PageBundle\Entity\Page
            mappedBy: parent
            orderBy:
                lft: ASC
        page_blocks:
            targetEntity: Zorbus\PageBundle\Entity\PageBlock
            mappedBy: page