parameters:
    zorbus_page.page.admin.class: Zorbus\PageBundle\Admin\PageAdmin
    zorbus_page.page_block.admin.class: Zorbus\PageBundle\Admin\PageBlockAdmin

    zorbus_page.page.entity.class: Zorbus\PageBundle\Entity\Page
    zorbus_page.page_block.entity.class: Zorbus\PageBundle\Entity\PageBlock

    zorbus_page.page.controller.class: ZorbusPageBundle:Admin\Page
    zorbus_page.page_block.controller.class: SonataAdminBundle:CRUD

    zorbus_page.page_theme.two.class: Zorbus\PageBundle\Model\PageThemeTwo
    zorbus_page.page_theme.three.class: Zorbus\PageBundle\Model\PageThemeThree
    zorbus_page.router.class: Zorbus\PageBundle\Router\PageRouter

services:
    zorbus_page.page.admin:
        class: %zorbus_page.page.admin.class%
        arguments: [~, %zorbus_page.page.entity.class%, %zorbus_page.page.controller.class%]
        calls:
            - [setTranslationDomain, [PageBundle]]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Pages, label: Page }
    zorbus_page.compiler.page_themes.config:
        class: Zorbus\PageBundle\DependencyInjection\Compiler\PageThemeCompilerConfig
    zorbus_page.form.type.page_themes:
        class: Zorbus\PageBundle\Form\Type\PageThemesType
        arguments:
            - '@zorbus_page.compiler.page_themes.config'
        tags:
            - { name: form.type, alias: page_themes }
    zorbus_page.page_theme.two:
        class: %zorbus_page.page_theme.two.class%
        tags:
            - { name: zorbus_page.theme }
    zorbus_page.page_theme.three:
        class: %zorbus_page.page_theme.three.class%
        tags:
            - { name: zorbus_page.theme }
    zorbus_page.router:
        class: %zorbus_page.router.class%
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: router, priority: 300 }