parameters:
    zorbus.page.admin.class: Zorbus\PageBundle\Admin\PageAdmin
    zorbus.page_block.admin.class: Zorbus\PageBundle\Admin\PageBlockAdmin

    zorbus.page.controller.class: ZorbusPageBundle:Admin
    zorbus.page_block.controller.class: SonataAdminBundle:CRUD
    
    zorbus.page.router.class: Zorbus\PageBundle\Router\PageRouter
        
    zorbus.page.theme.compiler.config.class: Zorbus\PageBundle\DependencyInjection\Compiler\PageThemeCompilerConfig
    zorbus.page.theme.form.type.class: Zorbus\PageBundle\Form\Type\PageThemesType
    
    zorbus.page.theme.two_column.class: Zorbus\PageBundle\Theme\TwoColumnTheme
    zorbus.page.theme.two_column.enabled: true
    zorbus.page.theme.three_column.class: Zorbus\PageBundle\Theme\ThreeColumnTheme
    zorbus.page.theme.three_column.enabled: true
    
services:
    zorbus.page.admin:
        class: %zorbus.page.admin.class%
        arguments: [~, %zorbus.page.entities.page%, %zorbus.page.controller.class%]
        calls:
            - [setTranslationDomain, [ZorbusPageBundle]]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Pages, label: Pages }
    zorbus.page.theme.compiler.config:
        class: %zorbus.page.theme.compiler.config.class%
    zorbus.page.theme.form.type:
        class: %zorbus.page.theme.form.type.class%
        arguments:
            - @zorbus.page.theme.compiler.config
        tags:
            - { name: form.type, alias: zorbus_page_themes }
    zorbus.page.theme.two_column:
        class: %zorbus.page.theme.two_column.class%
        arguments:
            - %zorbus.page.theme.two_column.enabled%
        tags:
            - { name: zorbus.page.theme }
    zorbus.page.theme.three_column:
        class: %zorbus.page.theme.three_column.class%
        arguments: 
            - %zorbus.page.theme.three_column.enabled%
        tags:
            - { name: zorbus.page.theme }
    zorbus.page.router:
        class: %zorbus.page.router.class%
        arguments: 
            - @doctrine.orm.entity_manager
            - %zorbus.page.entities.page%
        tags:
            - { name: cmf_routing.router }