parameters:
    zorbus_page.page.admin.class: Zorbus\PageBundle\Admin\PageAdmin
    zorbus_page.page_block.admin.class: Zorbus\PageBundle\Admin\PageBlockAdmin

    zorbus_page.page.entity.class: Zorbus\PageBundle\Entity\Page
    zorbus_page.page_block.entity.class: Zorbus\PageBundle\Entity\PageBlock

    zorbus_page.page.controller.class: SonataAdminBundle:CRUD
    zorbus_page.page_block.controller.class: SonataAdminBundle:CRUD

services:
    sonata.admin.page.page:
        class: %zorbus_page.page.admin.class%
        arguments: [~, %zorbus_page.page.entity.class%, %zorbus_page.page.controller.class%]
        calls:
            - [setTranslationDomain, [PageBundle]]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Pages, label: Page }
    sonata.admin.page.page_block:
        class: %zorbus_page.page_block.admin.class%
        arguments: [~, %zorbus_page.page_block.entity.class%, %zorbus_page.page_block.controller.class%]
        calls:
            - [setTranslationDomain, [PageBundle]]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Pages, label: Block to Page }
