<?php

namespace Zorbus\PageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PageBlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageBlockRepository extends EntityRepository
{
}
