<?php

namespace Zorbus\PageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository
{
    public function getBlocks($page_id)
    {
        $page_blocks = $this
                ->getEntityManager()
                ->createQuery('SELECT pb FROM ZorbusPageBundle:PageBlock pb JOIN pb.page p JOIN pb.block b WHERE p.id=:page_id ORDER BY pb.location ASC, pb.position ASC')
                ->setParameter('page_id', $page_id)
                ->getResult();

        $blocks = array();
        foreach ($page_blocks as $page_block)
        {
            $blocks[$page_block->getLocation()][] = $page_block->getBlock();
        }

        return $blocks;
    }
}
